server:
  port: 8081
  servlet:
    context-path: /smart-adder-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab2
    password: zsecsq
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_by:
          default_null_ordering: last
        format_sql: true
mockapi:
  url: "https://62fb7b6aabd610251c09e7e5.mockapi.io/api/v1/getBookByTitleAndAuthor/"