server:
  port: 8080
  servlet:
    context-path: /smart-adder-service
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab2
    password: zsecsq
    username: postgres
    driver-class-name: org.postgresql.Driver
    hikari.maximum-pool-size: 20
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect